### ISSUE TITLE
Lab1

### ISSUE THREAD

**Issue by AlekseiMaslakov** [ArturNurtdinov/java-labs#2]
Здравствуйте
Отрефакторьте код пожайлуста, пока это больше похоже на непонятное нагромождение разрозненных сущностей - один мэйн на 113 строк.

**Comment by ArturNurtdinov** [comment]
@AlekseiMaslakov, здравствуйте, попробовал разделить логику в мейне
Есть один вопрос касаемо `static` функций:
-В классе `Main` определена функция printBookList(...), почему её обязательно нужно сделать `static`, чтобы использовать в функции `main()`? Ведь например в классе `Task2` есть 
не `static` функция`getRandomChar()` и её я могу использовать в других функциях класса `Task2`.
Из-за того ли это что функции должны быть либо обе `static`, либо обе не `static`

**Comment by AlekseiMaslakov** [comment]
Да, в статических методах можно вызывать только статические методы, либо нужно создавать экземпляр класса и уже у него вызывать не статический метод.

**Comment by AlekseiMaslakov** [comment]
Уже лучше выглядит, но можно ещё:
- вынести свитч в класс Task3 - разве не там он должен быть?
- сделать из статических полей локальные переменные - зачем поля, если они нигде не используются?
- в мэйне и классе BookList одинаковые методы print - может быть оставить один из них?
- поля класса объявляются в начале, а не в конце (BookList)

**Comment by ArturNurtdinov** [comment]
@AlekseiMaslakov исправил замечания

**Comment by AlekseiMaslakov** [comment]
Осталась пара пунктов:
1) Раскидать всё по пакетам, а не сваливать всё в 1 папку
2) Task3 кидает ексепшн, который никто нигде не обрабатывает, следовательно работа программы завершается некорректно и с ошибкой

**Comment by ArturNurtdinov** [comment]
@AlekseiMaslakov, не думал, что аж с первой лабы начнём кидать по пакетам, но сделал

**Comment by AlekseiMaslakov** [comment]
А почему не начать сразу делать, как надо?)

scanner.nextInt() тоже будет кидать ошибку, при вводе не цифровых значений, но это уже так, можете исправить, можете так оставить
