### ISSUE TITLE
Lab 2

### ISSUE THREAD

**Issue by ArturNurtdinov** [ArturNurtdinov/java-labs#4]

**Comment by ArturNurtdinov** [comment]
@AlekseiMaslakov, залил вторую лабу и открыл issue для неё

**Comment by ArturNurtdinov** [comment]
Алексей Павлович, в каком порядке должны идти свойства базового класса Animal? У нас имеются конструктор, Override метод, абстрактный метод и пара геттеров. Как в этом случае расположить их стоит?

**Comment by AlekseiMaslakov** [comment]
Здравствуйте
Располагают обычно так:
- поля
- конструкторы
- методы, где будет абстрактный в принципе не особо важно, лично рекомендаций на этот счёт не видел и не получал
- геттеры/сеттеры (они конечно тоже методы, но их никто не читает)
